Add Stax, Flex devices support, update SDK
LedgerHQ/app-sui pull request #13
Opened 2024-12-30 21:31 UTC by dfordivam

# Checklist

- [ ] App update process has been followed 
- [ ] Target branch is `develop` 
- [ ] Application version has been bumped

2025-01-03 13:55 UTC, yogh333 requested changes
Could you please update to the last SDK and fix also any lint errors when running CI ?
Thanks !

2025-01-03 13:55 UTC, yogh333 commented on rust-app/Cargo.toml
> +ledger_secure_sdk_sys = "1.5.3"
Could you please update to last versions:
- ledger_device_sdk = `1.19.1`
- ledger_secure_sdk_sys = `1.6.1`
Thank you 🙏 !

2025-01-03 13:55 UTC, yogh333 commented on rust-app/Cargo.toml
> +version = "1.18.4"
`1.19.1`

2025-01-06 06:37 UTC, dfordivam commented on rust-app/Cargo.toml
> +version = "1.18.4"
Fixed

2025-01-06 06:37 UTC, dfordivam commented on rust-app/Cargo.toml
> +ledger_secure_sdk_sys = "1.5.3"
Fixed

2025-01-06 07:52 UTC, dfordivam commented
@yogh333 The SDK has been updated and the lint warnings are all resolved with latest rust nightly toolchain.

2025-01-08 14:38 UTC, yogh333 approved these changes

2025-01-08 14:39 UTC, merged